### ISSUE TITLE
Does not startup correctly

### ISSUE THREAD

**Issue by MrAlexEsisteGia** [Timeraa/YT-Presence#6] opened 2018-09-12 11:49 UTC
When YT-Presence auto startes up it does not connect to discord
![image](https://user-images.githubusercontent.com/24595840/45423034-573e9600-b692-11e8-8c16-5b9c16c6e222.png)
So i need to restart it manually

Possible problem:
My discord does not start up automatically

1. Start windows

 - OS: Windows 10
 - Browser Opera
 - Version 0.3

**Comment by Timeraa** [comment] 2018-09-15 17:57
First of all Thanks, thats an error in this version and i have a question, do Chrome extensions work on Opera? Because i only mentioned it works on Chrome. If so please tell me so i can update the Readme file.

**Comment by Timeraa** [comment] 2018-09-15 23:05
Ah, I found out some great stuff that allows me to add media key support (play pause buttons on keyboard) and a lot more :P

**Comment by MrAlexEsisteGia** [comment] 2018-09-16 21:56
It works perfectly on opera and without the "Install chrome extensions" if you want i can do a pull of a tutorial/help on how to do it on opera

**Comment by Timeraa** [comment] 2018-09-17 11:07
I would really appreciate if you could do that @MrAlexEsisteGia

**Comment by MrAlexEsisteGia** [comment] 2018-09-17 13:40
Done! :D

**Comment by Timeraa** [comment] 2018-09-17 19:13
Yeah i already know about that tip, but the problem is i have to basically create my own installer GUI on Windows, idk why but i will look into that really soon. Just need to finish the rewrites of a lot of stuff.

**Comment by Timeraa** [comment] 2018-10-07 14:07
Autostart issue fixed in V1.0 releasing really really soon.

**Closed by Timeraa** 2018-10-07 14:07 UTC
Labels: bug
